### ISSUE TITLE
Password in browser

### ISSUE THREAD

**Issue by mph070770** [mikecann/disco-cube-admin#10]
Hi @mikecann.  I'm presented with a password when I run the code.  I expected this to be my firebase password but that fails.  This is all quite new to me but I'd love to try your SW (as I have build a cube).  Can you help please?

**Comment by mph070770** [comment]
ok.  found the problem.  your email address was hardcoded in firebase.ts. :-)

**Comment by mikecann** [comment]
@mph070770 ye :P sorry about that!
